# Change these first
owner: caliphdev # Your GitHub organization or username, where this repository lives
repo: tiklydown-stats # The name of this repository

sites:
  - name: API
    url: https://developers.tiklydown.me
  - name: Website
    url: https://tiklydown.me/api/check

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tiklydown.me
  # baseUrl: /your-repo-name
  logoUrl: https://tiklydown.me/assets/img/icon-512x512.png
  name: Tiklydown Status
  introTitle: 
  introMessage: 
  navbar:
    - title: API
      href: https://developers.tiklydown.me
    - title: Website
      href: https://tiklydown.me

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
